DELETE FROM POKEMON_ABILITY;
DELETE FROM ABILITY;
DELETE FROM sqlite_sequence WHERE name = 'ABILITY';

-- Generating all pokemon abilities
INSERT INTO ABILITY (name, description) VALUES
('Stench', 'Has a 10% chance of making target Pokémon flinch with each hit.'),
('Drizzle', 'Summons rain that lasts indefinitely upon entering battle.'),
('Speed Boost', 'Raises Speed one stage after each turn.'),
('Battle Armor', 'Protects against critical hits.'),
('Sturdy', 'Prevents the Pokémon from being knocked out in one hit.'),
('Damp', 'Prevents Self-Destruct, Explosion, and Aftermath from working.'),
('Limber', 'Prevents paralysis.'),
('Sand Veil', 'Increases evasion during a sandstorm.'),
('Static', 'Has a 30% chance of paralyzing attacking Pokémon on contact.'),
('Volt Absorb', 'Heals for 1/4 max HP when hit by an Electric move.'),
('Water Absorb', 'Heals for 1/4 max HP when hit by a Water move.'),
('Oblivious', 'Prevents infatuation and protects against Captivate.'),
('Cloud Nine', 'Negates all effects of weather.'),
('Compound Eyes', 'Increases moves accuracy to 1.3x.'),
('Insomnia', 'Prevents sleep.'),
('Color Change', 'Changes type to match when hit by a damaging move.'),
('Immunity', 'Prevents poison.'),
('Flash Fire', 'Protects against Fire moves and powers up own Fire moves.'),
('Shield Dust', 'Protects against incoming moves extra effects.'),
('Own Tempo', 'Prevents confusion.'),
('Suction Cups', 'Prevents the Pokémon from being forced to switch out.'),
('Intimidate', 'Lowers opponents Attack one stage upon entering battle.'),
('Shadow Tag', 'Prevents opponents from fleeing or switching out.'),
('Rough Skin', 'Damages attacking Pokémon on contact.'),
('Wonder Guard', 'Only allows super-effective moves to hit.'),
('Levitate', 'Gives full immunity to all Ground-type moves.'),
('Effect Spore', '30% chance of inflicting status condition on contact.'),
('Synchronize', 'Passes on a status condition to the attacker.'),
('Clear Body', 'Prevents stats from being lowered by other Pokémon.'),
('Natural Cure', 'Cures any status ailment upon switching out.'),
('Lightning Rod', 'Redirects and absorbs single-target Electric moves.'),
('Serene Grace', 'Doubles the chance of moves extra effects occurring.'),
('Swift Swim', 'Doubles Speed during rain.'),
('Chlorophyll', 'Doubles Speed during strong sunlight.'),
('Illuminate', 'Doubles the wild encounter rate.'),
('Trace', 'Copies an opponents Ability upon entering battle.'),
('Huge Power', 'Doubles the Pokémons Attack stat.'),
('Poison Point', 'Has a 30% chance of poisoning attacking Pokémon on contact.'),
('Inner Focus', 'Prevents the Pokémon from flinching.'),
('Magma Armor', 'Prevents the Pokémon from becoming frozen.'),
('Water Veil', 'Prevents the Pokémon from becoming burned.'),
('Magnet Pull', 'Prevents Steel opponents from fleeing or switching out.'),
('Soundproof', 'Protects against sound-based moves.'),
('Rain Dish', 'Heals for 1/16 max HP each turn during rain.'),
('Sand Stream', 'Summons a sandstorm upon entering battle.'),
('Pressure', 'Increases the PP cost of moves targeting the Pokémon.'),
('Thick Fat', 'Halves damage from Fire and Ice-type moves.'),
('Early Bird', 'Makes sleep pass twice as quickly.'),
('Flame Body', 'Has a 30% chance of burning attacking Pokémon on contact.'),
('Run Away', 'Ensures success fleeing from wild battles.'),
('Keen Eye', 'Prevents accuracy from being lowered.'),
('Hyper Cutter', 'Prevents Attack from being lowered by other Pokémon.'),
('Pickup', 'May pick up an item after battle.'),
('Truant', 'Pokémon can only attack every other turn.'),
('Hustle', 'Strengthens physical moves but decreases accuracy.'),
('Cute Charm', '30% chance of infatuating attacking Pokémon on contact.'),
('Plus', 'Increases Special Attack if a friendly Pokémon has Minus.'),
('Minus', 'Increases Special Attack if a friendly Pokémon has Plus.'),
('Forecast', 'Changes Castforms type and form to match the weather.'),
('Sticky Hold', 'Prevents the Pokémon from losing its held item.'),
('Shed Skin', '33% chance of curing any major status ailment after each turn.'),
('Guts', 'Increases Attack by 1.5x with a status ailment.'),
('Marvel Scale', 'Increases Defense by 1.5x with a status ailment.'),
('Liquid Ooze', 'Damages opponents using HP-leeching moves.'),
('Overgrow', 'Strengthens Grass moves when HP is low.'),
('Blaze', 'Strengthens Fire moves when HP is low.'),
('Torrent', 'Strengthens Water moves when HP is low.'),
('Swarm', 'Strengthens Bug moves when HP is low.'),
('Rock Head', 'Protects against recoil damage.'),
('Drought', 'Summons strong sunlight upon entering battle.'),
('Arena Trap', 'Prevents opponents from fleeing or switching out.'),
('Vital Spirit', 'Prevents the Pokémon from falling asleep.'),
('White Smoke', 'Prevents other Pokémon from lowering its stats.'),
('Pure Power', 'Doubles the Pokémons Attack stat.'),
('Shell Armor', 'Protects against critical hits.'),
('Air Lock', 'Eliminates the effects of weather.');

-- Generating all pokemon moves
INSERT INTO MOVE (name, type_id) VALUES
('Pound', 1), ('Karate Chop', 7), ('Double Slap', 1), ('Comet Punch', 1), ('Mega Punch', 1),
('Pay Day', 1), ('Fire Punch', 2), ('Ice Punch', 6), ('Thunder Punch', 5), ('Scratch', 1),
('Vice Grip', 1), ('Guillotine', 1), ('Razor Wind', 1), ('Swords Dance', 1), ('Cut', 1),
('Gust', 10), ('Wing Attack', 10), ('Whirlwind', 1), ('Fly', 10), ('Bind', 1),
('Slam', 1), ('Vine Whip', 4), ('Stomp', 1), ('Double Kick', 7), ('Mega Kick', 1),
('Jump Kick', 7), ('Rolling Kick', 7), ('Sand Attack', 9), ('Headbutt', 1), ('Horn Attack', 1),
('Fury Attack', 1), ('Horn Drill', 1), ('Tackle', 1), ('Body Slam', 1), ('Wrap', 1),
('Take Down', 1), ('Thrash', 1), ('Double-Edge', 1), ('Tail Whip', 1), ('Poison Sting', 8),
('Twineedle', 12), ('Pin Missile', 12), ('Leer', 1), ('Bite', 17), ('Growl', 1),
('Roar', 1), ('Sing', 1), ('Supersonic', 1), ('Sonic Boom', 1), ('Disable', 1),
('Acid', 8), ('Ember', 2), ('Flamethrower', 2), ('Mist', 6), ('Water Gun', 3),
('Hydro Pump', 3), ('Surf', 3), ('Ice Beam', 6), ('Blizzard', 6), ('Psybeam', 11),
('Bubble Beam', 3), ('Aurora Beam', 6), ('Hyper Beam', 1), ('Peck', 10), ('Drill Peck', 10),
('Submission', 7), ('Low Kick', 7), ('Counter', 7), ('Seismic Toss', 7), ('Strength', 1),
('Absorb', 4), ('Mega Drain', 4), ('Leech Seed', 4), ('Growth', 1), ('Razor Leaf', 4),
('Solar Beam', 4), ('Poison Powder', 8), ('Stun Spore', 4), ('Sleep Powder', 4), ('Petal Dance', 4),
('String Shot', 12), ('Dragon Rage', 15), ('Fire Spin', 2), ('Thunder Shock', 5), ('Thunderbolt', 5),
('Thunder Wave', 5), ('Thunder', 5), ('Rock Throw', 13), ('Earthquake', 9), ('Fissure', 9),
('Dig', 9), ('Toxic', 8), ('Confusion', 11), ('Psychic', 11), ('Hypnosis', 11),
('Meditate', 11), ('Agility', 11), ('Quick Attack', 1), ('Rage', 1), ('Teleport', 11),
('Night Shade', 14), ('Mimic', 1), ('Screech', 1), ('Double Team', 1), ('Recover', 1),
('Harden', 1), ('Minimize', 1), ('Smokescreen', 1), ('Confuse Ray', 14), ('Withdraw', 3),
('Defense Curl', 1), ('Barrier', 11), ('Light Screen', 11), ('Haze', 6), ('Reflect', 11),
('Focus Energy', 1), ('Bide', 1), ('Metronome', 1), ('Mirror Move', 10), ('Self-Destruct', 1),
('Egg Bomb', 1), ('Lick', 14), ('Smog', 8), ('Sludge', 8), ('Bone Club', 9),
('Fire Blast', 2), ('Waterfall', 3), ('Clamp', 3), ('Swift', 1), ('Skull Bash', 1),
('Spike Cannon', 1), ('Constrict', 1), ('Amnesia', 11), ('Kinesis', 11), ('Soft-Boiled', 1),
('High Jump Kick', 7), ('Glare', 1), ('Dream Eater', 11), ('Poison Gas', 8), ('Barrage', 1),
('Leech Life', 12), ('Lovely Kiss', 1), ('Sky Attack', 10), ('Transform', 1), ('Bubble', 3),
('Dizzy Punch', 1), ('Spore', 4), ('Flash', 1), ('Psywave', 11), ('Splash', 3),
('Acid Armor', 8), ('Crabhammer', 3), ('Explosion', 1), ('Fury Swipes', 1), ('Bonemerang', 9),
('Rest', 11), ('Rock Slide', 13), ('Hyper Fang', 1), ('Sharpen', 1), ('Conversion', 1),
('Tri Attack', 1), ('Super Fang', 1), ('Slash', 1), ('Substitute', 1), ('Struggle', 1),
('Sketch', 1), ('Triple Kick', 7), ('Thief', 17), ('Spider Web', 12), ('Mind Reader', 1),
('Nightmare', 14), ('Flame Wheel', 2), ('Snore', 1), ('Curse', 14), ('Flail', 1),
('Conversion 2', 1), ('Aeroblast', 10), ('Cotton Spore', 4), ('Reversal', 7), ('Spite', 14),
('Powder Snow', 6), ('Protect', 1), ('Mach Punch', 7), ('Scary Face', 1), ('Faint Attack', 17),
('Sweet Kiss', 1), ('Belly Drum', 1), ('Sludge Bomb', 8), ('Mud-Slap', 9), ('Octazooka', 3),
('Spikes', 9), ('Zap Cannon', 5), ('Foresight', 1), ('Destiny Bond', 14), ('Perish Song', 1),
('Icy Wind', 6), ('Detect', 7), ('Bone Rush', 9), ('Lock-On', 1), ('Outrage', 15),
('Sandstorm', 13), ('Giga Drain', 4), ('Endure', 1), ('Charm', 1), ('Rollout', 13),
('False Swipe', 1), ('Swagger', 1), ('Milk Drink', 1), ('Spark', 5), ('Fury Cutter', 12),
('Steel Wing', 16), ('Mean Look', 1), ('Attract', 1), ('Sleep Talk', 1), ('Heal Bell', 1),
('Return', 1), ('Present', 1), ('Frustration', 1), ('Safeguard', 1), ('Pain Split', 1),
('Sacred Fire', 2), ('Magnitude', 9), ('Dynamic Punch', 7), ('Megahorn', 12), ('Dragon Breath', 15),
('Baton Pass', 1), ('Encore', 1), ('Pursuit', 17), ('Rapid Spin', 1), ('Sweet Scent', 1),
('Iron Tail', 16), ('Hidden Power', 1), ('Cross Chop', 7), ('Twister', 15), ('Rain Dance', 3),
('Sunny Day', 2), ('Crunch', 17), ('Mirror Coat', 11), ('Psych Up', 1), ('Extreme Speed', 1),
('Ancient Power', 13), ('Shadow Ball', 14), ('Future Sight', 11), ('Rock Smash', 7), ('Whirlpool', 3),
('Beat Up', 17), ('Fake Out', 1), ('Uproar', 1), ('Stockpile', 1), ('Spit Up', 1),
('Swallow', 1), ('Heat Wave', 2), ('Hail', 6), ('Torment', 17), ('Flatter', 17),
('Will-O-Wisp', 2), ('Memento', 17), ('Facade', 1), ('Focus Punch', 7), ('Smelling Salt', 1),
('Follow Me', 1), ('Nature Power', 1), ('Charge', 5), ('Taunt', 17), ('Helping Hand', 1),
('Trick', 11), ('Role Play', 11), ('Wish', 1), ('Assist', 1), ('Ingrain', 4),
('Superpower', 7), ('Magic Coat', 11), ('Recycle', 1), ('Revenge', 7), ('Brick Break', 7),
('Yawn', 1), ('Knock Off', 17), ('Endeavor', 1), ('Eruption', 2), ('Skill Swap', 11),
('Imprison', 11), ('Refresh', 1), ('Grudge', 14), ('Snatch', 17), ('Secret Power', 1),
('Dive', 3), ('Arm Thrust', 7), ('Camouflage', 1), ('Tail Glow', 12), ('Luster Purge', 11),
('Mist Ball', 11), ('Feather Dance', 10), ('Teeter Dance', 1), ('Blaze Kick', 2), ('Mud Sport', 9),
('Ice Ball', 6), ('Needle Arm', 4), ('Slack Off', 1), ('Hyper Voice', 1), ('Poison Fang', 8),
('Crush Claw', 1), ('Blast Burn', 2), ('Hydro Cannon', 3), ('Meteor Mash', 16), ('Astonish', 14),
('Weather Ball', 1), ('Aromatherapy', 4), ('Fake Tears', 17), ('Air Cutter', 10), ('Overheat', 2),
('Odor Sleuth', 1), ('Rock Tomb', 13), ('Silver Wind', 12), ('Metal Sound', 16), ('Grass Whistle', 4),
('Tickle', 1), ('Cosmic Power', 11), ('Water Spout', 3), ('Signal Beam', 12), ('Shadow Punch', 14),
('Extrasensory', 11), ('Sky Uppercut', 7), ('Sand Tomb', 9), ('Sheer Cold', 6), ('Muddy Water', 3),
('Bullet Seed', 4), ('Aerial Ace', 10), ('Icicle Spear', 6), ('Iron Defense', 16), ('Block', 1),
('Howl', 1), ('Dragon Claw', 15), ('Frenzy Plant', 4), ('Bulk Up', 7), ('Bounce', 10),
('Mud Shot', 9), ('Poison Tail', 8), ('Covet', 1), ('Volt Tackle', 5), ('Magical Leaf', 4),
('Water Sport', 3), ('Calm Mind', 11), ('Leaf Blade', 4), ('Dragon Dance', 15), ('Rock Blast', 13),
('Shock Wave', 5), ('Water Pulse', 3), ('Doom Desire', 16), ('Psycho Boost', 11);